### PR TITLE
Unit tests

### PR DESCRIPTION
**Pull request by echen94**
Bug fix for multiple nested config

### CODE REVIEW

**Comment by ghost** [comment]
Good fix. It would be better if we can find more bugs......

**Comment by ghost** [comment]
Good fix!

**Comment by ghost** [comment]
It would be better if there are more test cases!

**Comment by echen94** [comment]
Added more test cases and fixed another bug (unmatched parenthesis)

**Comment by zxxia** [comment]
Thank you. To me, both bugs are fixed.

Is it ok if we push new files like .o files and executable files on to unit-tests branch?

**Pull request merged**
